//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anastasia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int SongId { get; set; }
        public int SongListNumber { get; set; }
        public string SongImage { get; set; }
        public string SongTitle { get; set; }
        public string SongSubtitle { get; set; }
        public string SongLink { get; set; }
    }
}
